[project]
name = "syndiff"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "h5py>=3.15.1",
    "ninja>=1.13.0",
    "scikit-image>=0.25.2",
    "setuptools>=80.9.0",
]
